version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "php"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"

[[transformers]]
name = "php-cs-fixer"